[package]
name = "taiko-copy"
version = "0.1.0"
authors = ["jojo <jojolepromain@gmail.com>"]

[dependencies]
amethyst = "0.5.1"
futures = "*"
rayon = "*"
rand = "0.3.16"
time = "0.1"
winit = "0.7"
amethyst_input = "*"
